# Module 3b: Dimension Reduction using Linear Discriminant Analysis (LDA)
Charles Pang, PSUPR Sep 2023 <br><br>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix, classification_report, precision_score

## Load the Dataset

In [3]:
# we will be using a diabetes dataset with no missing values (ref: KNN Imputer)
data = pd.read_csv('diabetes_imputed.csv')
X = data.drop('Outcome',axis=1)
y = data[:]['Outcome']

colnames = list(data) #good way to extract column names from dataframe

In [4]:
colnames

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']

In [6]:
X.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,400.2,33.60,0.627,50.0
1,1.0,85.0,66.0,29.0,65.2,26.60,0.351,31.0
2,8.0,183.0,64.0,28.8,186.0,23.30,0.672,32.0
3,1.0,89.0,66.0,23.0,94.0,28.10,0.167,21.0
4,0.0,137.0,40.0,35.0,168.0,43.10,2.288,33.0
5,5.0,116.0,74.0,23.0,128.4,25.60,0.201,30.0
6,3.0,78.0,50.0,32.0,88.0,31.00,0.248,26.0
7,10.0,115.0,72.0,31.8,219.6,35.30,0.134,29.0
8,2.0,197.0,70.0,45.0,543.0,30.50,0.158,53.0
9,8.0,125.0,96.0,33.0,282.2,33.02,0.232,54.0

# Split Train and Test

In [5]:
# No need for standardizaion in LDA
# Split Training & Testing datasets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state=123)

# Apply the LDA

In [7]:
lda = LDA()
X_train = lda.fit(X_train, y_train)

# Percentage of class labels (0 or 1)
print("Model Priors:\n",lda.priors_)

Model Priors:
 [0.66480447 0.33519553]

# Coefficients

In [9]:
lda.coef_

array([[ 0.12702251,  0.03380551, -0.00990918,  0.00478489,  0.00192998,
         0.08001212,  0.72245833,  0.01223322]])

In [10]:
# Binary classification will result in 1 Component only
lda_coef = pd.DataFrame(np.transpose(lda.coef_), index=list(X))
print("\nLDA Coefficients:\n",lda_coef)

LDA Coefficients:
                                  0
Pregnancies               0.127023
Glucose                   0.033806
BloodPressure            -0.009909
SkinThickness             0.004785
Insulin                   0.001930
BMI                       0.080012
DiabetesPedigreeFunction  0.722458
Age                       0.012233

# Apply LDA on the Test set

In [14]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
236,7.0,181.0,84.0,21.0,192.0,35.9,0.586,51.0
395,2.0,127.0,58.0,24.0,275.0,27.7,1.600,25.0
36,11.0,138.0,76.0,33.8,174.6,33.2,0.420,35.0
210,2.0,81.0,60.0,22.0,68.4,27.7,0.290,25.0
483,0.0,84.0,82.0,31.0,125.0,38.2,0.233,23.0
...,...,...,...,...,...,...,...,...
122,2.0,107.0,74.0,30.0,100.0,33.6,0.404,23.0
40,3.0,180.0,64.0,25.0,70.0,34.0,0.271,26.0
102,0.0,125.0,96.0,19.4,107.2,22.5,0.262,21.0
751,1.0,121.0,78.0,39.0,74.0,39.0,0.261,28.0
289,5.0,108.0,72.0,43.0,75.0,36.1,0.263,33.0

In [13]:
lda.predict(X_test)

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [15]:
y_test

236    1
395    0
36     0
210    0
483    0
      ..
122    0
40     0
102    0
751    0
289    0
Name: Outcome, Length: 231, dtype: int64

In [17]:
pred=lda.predict(X_test)
print(np.unique(pred, return_counts=True))
confmatrix = pd.DataFrame(confusion_matrix(pred, y_test, labels=[0,1]), index=[0,1])
print("\nConfusion Matrix:\n", confmatrix)
print('\n')
print(classification_report(y_test, pred, digits=3))

(array([0, 1]), array([161,  70]))

Confusion Matrix:
      0   1
0  130  31
1   13  57


              precision    recall  f1-score   support

           0      0.807     0.909     0.855       143
           1      0.814     0.648     0.722        88

    accuracy                          0.810       231
   macro avg      0.811     0.778     0.788       231
weighted avg      0.810     0.810     0.804       231

# Using LDA to predict new data

In [20]:
# say we have a new case and we want to predict diabetes
newpatient = [6,148,72,35,0,33.6,0.627,50]
diagnosis = lda.predict([newpatient])
print('Predicted Class: %d' % diagnosis)
print('Predicted Class: ', diagnosis)

Predicted Class: 1
Predicted Class:  [1]

/hpctmp/e1554287/conda/envs/ai1008/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(
/var/tmp/pbs.226548.venus01/ipykernel_9776/369988440.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('Predicted Class: %d' % diagnosis)